apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chachkies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/poprygun/chachkies-builder.git
    targetRevision: HEAD
    path: argo/chachkies
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false